import HeadingAdmin from '@/components/admin/heading-admin';
import { getAllChordFamilies } from '@/src/server/data/families.query';
import { Metadata } from 'next';
import { ChordFamiliesColumns } from './components/table/Columns';
import { DataTable } from '@/components/ui/data-table';


export const metadata: Metadata = {
  title: "Admin - Familles",
  description: "Generated by create next app",
};

const AdminFamiliesPage = async () => {
  //*** DATAS ***//
  const data = await getAllChordFamilies()
  if (!data) return <div>Aucun degrés trouvé...</div>

  const formattedChordFamiliesData: ChordFamiliesColumns[] = data.map(item => ({
    id: item.id,
    name: item.name,
    chordsCount: item.chords?.length || 0,
  }))
  return (
    <>
      <HeadingAdmin href={'/admin/familles/edition'} title={'Ajouter une famille'} />

      <section className='mx-auto p-3 md:p-5 lg:p-7'>
        {/* Data Table */}
        <div className='grid grid-cols-1 md:grid-cols-2'>
          <div className="px-2 w-fit">
            <DataTable columns={ChordFamiliesColumns} data={formattedChordFamiliesData} searchKey="name" />
          </div>
          <div className="px-2 w-fit">
            {/* <DataTable columns={ChordFamiliesColumns} data={formattedChordFamiliesData} searchKey="name" /> */}
          </div>

        </div>
      </section>
    </>
  )
}

export default AdminFamiliesPage