import HeadingAdmin from '@/components/admin/heading-admin';
import { getAllChordFamilies, getAllScaleFamilies } from '@/src/server/data/families.query';
import { Metadata } from 'next';
import { ChordFamiliesColumns, ScaleFamiliesColumns } from './components/table/Columns';
import { DataTable } from '@/components/ui/data-table';


export const metadata: Metadata = {
  title: "Admin - Familles",
  description: "Generated by create next app",
};

const AdminFamiliesPage = async () => {
  //*** DATAS ***//
  const allChordFamilies = await getAllChordFamilies();
  const allScaleFamilies = await getAllScaleFamilies();

  if (!allChordFamilies || !allScaleFamilies) return <div>Erreur lors de la récupération des données...</div>


  //*** FORMATTED DATAS***//
  const formattedChordFamiliesData: ChordFamiliesColumns[] = allChordFamilies.map(item => ({
    id: item.id,
    name: item.name,
  }))
  const formattedScaleFamiliesData: ScaleFamiliesColumns[] = allScaleFamilies.map(item => ({
    id: item.id,
    name: item.name,
  }))

  return (
    <>
      <HeadingAdmin href={'/admin/familles/edition'} title={'Ajouter une famille'} />

      <section className='mx-auto p-3 md:p-5 lg:p-7'>
        {/* Data Table */}
        <div className='grid grid-cols-1 md:grid-cols-2'>
          <div className="px-2 w-fit">
            <p className='text-sm font-semibold'>Familles d'accords</p>
            <DataTable columns={ChordFamiliesColumns} data={formattedChordFamiliesData} searchKey="name" />
          </div>
          <div className="px-2 w-fit">
            <p className='text-sm font-semibold'>Familles de gammes</p>
            <DataTable columns={ScaleFamiliesColumns} data={formattedScaleFamiliesData} searchKey="name" />
          </div>

        </div>
      </section>
    </>
  )
}

export default AdminFamiliesPage