import HeadingAdmin from '@/components/admin/heading-admin'
import React from 'react'
import { Metadata } from 'next';
import { getAllScaleIntervals } from '@/src/server/data/intervals.query';
import { getAllScaleFamilies } from '@/src/server/data/families.query';
import { getAllScaleNames } from '@/src/server/data/names.query';
import AddScaleForm from '../components/forms/add-scale.form';

export const metadata: Metadata = {
  title: "Admin - Gammes/Edition",
  description: "Generated by create next app",
};

const AdminEditScalePage = async () => {
  //*** DATAS ***//
  const scaleIntervals = await getAllScaleIntervals()
  const scaleFamilies = await getAllScaleFamilies()
  const allScaleNames = await getAllScaleNames()

  if (!scaleIntervals || !scaleFamilies || !allScaleNames) {
    return <div>Erreur lors de la récupération des données</div>
  }

  //*** FORMATTED DATAS ***//
  return (
    <>
      <HeadingAdmin />

      <section className='mx-auto p-3 md:p-5 lg:p-7 space-y-5'>
        {/* Form */}
        <AddScaleForm
          scaleIntervals={scaleIntervals}
          scaleFamilies={scaleFamilies}
          scaleNames={allScaleNames}
        />
      </section>
    </>
  )
}

export default AdminEditScalePage