import HeadingAdmin from '@/components/admin/heading-admin';
import { DataTable } from '@/components/ui/data-table';
import { getAllDegrees } from '@/src/server/data/degrees.query';
import { Metadata } from 'next';
import React from 'react'
import { DegreesColumns } from './components/table/Columns';


export const metadata: Metadata = {
  title: "Admin - Degrés",
  description: "Generated by create next app",
};


const AdminDegreesPage = async () => {
  //*** DATAS ***//
  const data = await getAllDegrees()
  if (!data) return <div>Aucun degrés trouvé...</div>

  const formattedData: DegreesColumns[] = data.map(item => ({
    id: item.id,
    content: item.content,
  }))
  return (
    <>
      <HeadingAdmin href={'/admin/accords/edition'} title={'Ajouter un accord'} />

      <section className='mx-auto p-3 md:p-5 lg:p-7'>
        {/* Data Table */}
        <div className="px-2 w-fit">
          <DataTable columns={DegreesColumns} data={formattedData} searchKey="content" />
        </div>
      </section>
    </>

  )
}

export default AdminDegreesPage