import HeadingAdmin from '@/components/admin/heading-admin'
import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Admin - Familles/Edition",
  description: "Generated by create next app",
};

const AdminEditFamilyPage = () => {
  return (
    <>
      <HeadingAdmin/>

      <section className='mx-auto p-3 md:p-5 lg:p-7 space-y-5'>
        {/* Form */}
        {/* <AddNoteForm /> */}

      </section>
    </>
  )
}

export default AdminEditFamilyPage