import HeadingAdmin from '@/components/admin/heading-admin'
import React from 'react'
import { Metadata } from 'next';
import { getAllChordIntervals } from '@/src/server/data/intervals.query';
import { getAllChordNames } from '@/src/server/data/names.query';
import { getAllChordFamilies } from '@/src/server/data/families.query';
import AddChordForm from '../components/forms/add-chord.form';

export const metadata: Metadata = {
  title: "Admin - Accords/Edition",
  description: "Generated by create next app",
};

const AdminEditChordPage = async () => {
  //*** DATAS ***//
  const chordIntervals = await getAllChordIntervals()
  const chordFamilies = await getAllChordFamilies()
  const allChordNames = await getAllChordNames()

  if (!chordIntervals || !chordFamilies || !allChordNames) {
    return <div>Erreur lors de la récupération des données</div>
  }

  //*** FORMATTED DATAS ***//
  return (
    <>
      <HeadingAdmin/>

      <section className='mx-auto p-3 md:p-5 lg:p-7 space-y-5'>
        {/* Form */}
        <AddChordForm
          chordIntervals={chordIntervals}
          chordFamilies={chordFamilies}
          chordNames={allChordNames}
        />
      </section>
    </>
  )
}

export default AdminEditChordPage