import HeadingAdmin from '@/components/admin/heading-admin';
import { Metadata } from 'next';
import React from 'react'


export const metadata: Metadata = {
  title: "Admin - Utilisateurs",
  description: "Generated by create next app",
};


const AdminUsersPage = () => {
  return (
    <>
      <HeadingAdmin title='Utilisateurs' />
    </>
  )
}

export default AdminUsersPage