import HeadingAdmin from '@/components/admin/heading-admin';
import { Metadata } from 'next';
import React from 'react'


export const metadata: Metadata = {
  title: "Admin - Dashboard",
  description: "Generated by create next app",
};


const AdminDashboard = () => {
  return (
    <>
      <HeadingAdmin title='Dashboard' />
    </>

  )
}

export default AdminDashboard