import HeadingAdmin from '@/components/admin/heading-admin';
import { Metadata } from 'next';
import AddScaleForm from './components/forms/scale.form';


export const metadata: Metadata = {
  title: "Admin - Gammes",
  description: "Generated by create next app",
};

const AdminScalePage = () => {
  return (
    <>
      <HeadingAdmin title='Gammes' />

      <section className='mx-auto p-3 md:p-5 lg:p-7 space-y-5'>

        <AddScaleForm />

        <div>Tableau</div>
      </section>

    </>
  )
}

export default AdminScalePage