import HeadingAdmin from "@/components/admin/heading-admin";
import { Metadata } from "next";
import AddTonalityForm from "../components/forms/add-tonality.form";

export const metadata: Metadata = {
  title: "Admin - Tonalite/Edition",
  description: "Generated by create next app",
};

const AdminTonalitiesEditionPage = () => {
  return (
    <>
      <HeadingAdmin/>

      <section className='mx-auto p-3 md:p-5 lg:p-7 space-y-5'>
        {/* Form */}
        <AddTonalityForm />

      </section>
    </>
  )
}

export default AdminTonalitiesEditionPage