import HeadingAdmin from '@/components/admin/heading-admin'
import React from 'react'
import { Metadata } from 'next';
import AddProgressionForm from '../components/forms/note.form';

export const metadata: Metadata = {
  title: "Admin - Progressions/Edition",
  description: "Generated by create next app",
};

const AdminEditChordsProgressionPage = () => {
  return (
    <>
      <HeadingAdmin />

      <section className='mx-auto p-3 md:p-5 lg:p-7 space-y-5'>
        {/* Form */}
        <AddProgressionForm />

      </section>
    </>
  )
}

export default AdminEditChordsProgressionPage