import HeadingAdmin from '@/components/admin/heading-admin';
import { getAllChords } from '@/src/server/data/chords.query';
import { Metadata } from 'next';
import React from 'react'
import { ChordsColumns } from './components/table/Columns';
import { DataTable } from '@/components/ui/data-table';


export const metadata: Metadata = {
  title: "Admin - Accords",
  description: "Generated by create next app",
};


const AdminChordsPage = async () => {
  //*** DATAS ***//
  const data = await getAllChords()
  if (!data) return <div>Aucun accord trouvé...</div>

  const formattedData: ChordsColumns[] = data.map(item => ({
    id: item.id,
    name: item.nameChord,
    tonalityId: item.tonalityId,
    modeId: item.modeId
  }))
  return (
    <>
      <HeadingAdmin href={'/admin/accords/edition'} title={'Ajouter un accord'} />

      <section className='mx-auto p-3 md:p-5 lg:p-7'>
        {/* Data Table */}
        <div className="px-2 w-fit">
          <DataTable columns={ChordsColumns} data={formattedData} searchKey="name" />
        </div>
      </section>
    </>

  )
}

export default AdminChordsPage