import HeadingAdmin from '@/components/admin/heading-admin';
import { Metadata } from 'next';
import ScaleIntervalForm from './components/forms/scale-interval.form';
import ChordIntervalForm from './components/forms/chord-interval.form';

export const metadata: Metadata = {
  title: "Admin - Intervalles",
  description: "Generated by create next app",
};

const AdminIntervalsPage = () => {
  return (
    <>
      <HeadingAdmin title='Intervalles' />

      <section className='grid grid-cols-1 xl:grid-cols-2 mx-auto p-3 md:p-5 lg:p-7'>

        <div>Tableau</div>

        <div className='space-y-5'>
          <ScaleIntervalForm />
          <ChordIntervalForm />
        </div>
      </section>

    </>
  )
}

export default AdminIntervalsPage